<MainView>:
    MDBoxLayout:
        MainViewSideBar:
            id: side_bar
            size_hint_x: None
            open_state: 'close'
        MDBoxLayout:
            orientation: 'vertical'
            padding: '8dp'
            MDScreenManager:
                id: mgr

            PlayerBarContainer:
                id: bar_container
                size_hint_y: None
                height: '0dp'
